info:
  name: "Test Lines"
  version: "2.0"
  date: 20160925
  author: "Joost De Cock"
  email: "joost@decock.org"
  company: "freesewing.org"
  link: "freesewing.org/pattern/joost-body-block/"
parts:
  test: "Lines test"
languages:
    en: English
    nl: Nederlands
