hidden: true
info:
    name: "Getting Started Guide"
    version: "1.0"
    date: 20170130
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"

parts:
    part: "A part"

languages:
    en: "English"

measurements:
    exampleMeasurement: 520

options:
    figure:
        type: "chooseOne"
        default: "ingredients"
