language: php

# These are the PHP versions we support
php:
- '5.6'
- '7.0'
- '7.1'

# Install sshpass for non-interactive ssh login
addons:
    apt:
        packages:
            - sshpass

# Intalling core
install:
- composer install --no-interaction
- composer dump-autoload -o

# Variables needed for auto-deploy
env:
  global:
  - secure: Ym39daVkIrHuyuemjbmi2qDuR3rTs/c5F9ed6zFhyMkrG3UskxwGcaUr4QBw4A1wFq4WgUr1kLz2zDJgbYpnJgdoLevvZ3GNZo73qVRPawA3MH4R3e3N1gUc2+1VM7u6fx1n8IqRLuOBpMxdWwXnd9z40Dvtz1GBDWrgRCBcxr7MI8vC32VZZbZ9vA2ffTb3X2CuR5ovVg7aT7xWQV924dy6kKONKmUNhegak3O9LKemvZY07Nc3LZ+53DKxx1IbbBIIQgtO7gLQeojrVjiNcP17vBZkoLgp7fLrsuqOgVK3Ph12gmqqJgS5t8Z9E2NYcWI1p9eCys2Mo6GOfj22cL900Ie8ca4Zsa38T+JXCoDsks7q17L41N1LNxxKoMOGYbufnGS8wpiv0WoGsuRvEaJfZMmy72xT5l3RFKUUsy3szhkLBULt1SE9HhxIYymyMCQcrdAsGMDPSZQAzDGNe35O9QNBxrB47r70Hdq9UV2/KlR1Racu47X3inK2ipAED4dRBjXGjtxuFxLoFXnx40U1CLZsYv52pyQX+oxDCk9KSNnTb1BznqlHC9zjISj0fdBHxdy9WVha/y/3bGKnaWg7p/UuXmlCfUseRobQvSLNQfky1Aov3rnemYS5ys8JcyEI6W0xdkTokvrwwr7NptLT3fB2G+XAPrssK9eNA58=
  - secure: fTdKKSM3qLGJd7EsB8cyv/ADwKSVQ7jwYvLXRtgV2SL7MvBppS1SCmQofwXnOXEcrfKPeN9cz3r4PINHrvIuYL/0Eu8zLaxVq+FtFhAs07DYTtezJ0ZILwY52Co5rlLVm1fLz+CC8PPnPZLVp7i8r1MKRjGsIFBXUmbAm6FeZK/8rGzWdVCeK5DjQmxEd69nB/GqiOQ1SsVWLaW2rrcndSKm5MYe0koNreRoj7XU5dwmU+Rv9lrWvv1940DAD/QeRWjI2elgZ+d2SgPiy6vGYhocua6xiDeVjeBXZTPY2/SqgbRTLI+iYiBwY7uqP93oL2XOZw8zTb3WHkPaxPnVSWIfCCYPKof32r8LdCHmWj4+XFbqKlHYVPTDW3cugB98cjgvkyDDGeyqP1/ZfcfN75knoN0nXn+fQCe2I4Tipkto8hAIYZQ5Ru/5XexL34D57eh9alkychi/FDNadHqFo/SAAlNU7pBd2N3N7KdTPzH6hVAflrlP6zhi6IAZh8v2yqW2IitZu2RHGnon5rzIYHZUciiIPK04EPoecOfcdE/w3EbdasezLb1jBhid+oU+vcVOTQFzHV+0vqowMEYaG+u3QoZGZXuIaw8+kMZNvxD1Mv32zFlZLD7ODGFKy4d538JWzDexMurmU8/s77wFPgfgYQGHMjDAAuzx00dg5/U=
  - secure: Pj8glZweQX48xrkChB7jD9uno2virogA/gt/viqUROa4K9yDIs7lO8sWO/Qqv1g/ISNrFpMGQPUBng0dC/hPO+fqLdT/HGAU2UGU/XFosJ7gQ5Y/bURwPIIVtfEClbHA1tb6ts/SdiJUz0KKT2H+baGaDf/sq8Wp8Rzo5DyP6NDepgxz5d08xFGLCFoqE6RTsCjMQHviuzj02I5uLP9UKanfd7NNN6tz8SOk3Lgh+e2PwWPgTj1yAs4rcgqrNn/3Ey56KhJmETP+NwJ3MT+j98r+Xp69D6MOvj0Q727aiY0pLWh6oQHWSYoWhWtCoVT/87lzA9iy08EDa8ZjmKN5VjLFzmVXkJtO5XmDpAx34Y5AnycfWAU6KwJ5UCm8eK46tC+W3qt+2Lb0wOINdyc1SRaB7VUdfYhZEgY2j46pVg/wTd1PFmKg2ZkxjAlnh7Dfnu8b4vXatzZwldYWkjAsgqezI+p5ocNm9BRrDd5wVRs//czTr9kLGk0VEELYzYwi++dPATF9qpvHCxcxz7NQ3ohVq2hCopXmfYQa+Rp+YyoTu56W1D9zpo8Bqhw+34h2nqbxFQ1JgJvUEaaj7tNkDINV8FT9IaGoBt16soo6VPC3uQXkWJ5lsWlGNgY5KHdCR8CV/WBnBbTUi/b8I73bBtnjWjtfLB+Mp/WGv8wlFPI=
  - secure: UofJQPEf/9e5epZiCB8DIJJ6K0GfdoEvOMnS17qI3hPvgsryCqsVQJ63+cMVc7ZLVtSRnzu2AqwBb5QLydLx4ccTO7qlo+A3LAx/fzQbohYU6GUM0ed9+8mVf+dma2ZEPsELd2ZUmdQ1Xds2/ubwJh77xIa/Kc8aprvhjaYkwmtqI+1Nd9CRU+qhD1qFPYaAaKZhr2lJE9geGg+8osepgJ30hFjsI7CGA+WDDcw1sjJaFCbntVr6qhgQPl62Eb+KRRYt5N+W0mQwLvO8rOcfSTbxLCgoE4Pv+6f4uF9vG/PTVxSW89NGsYt0R2o1Ia+D7m75EgYD+CwugOjYFrC8aCJEadQtov1VsVii0Vh3TXQC2KtoNmhYBTFLmJjh/ZaRIDch9x63b/E/nmmFIgbfr7fBgXx6GoUr7FmVyWQw31CTIENjULYWFeqpptysudoW8HMpNsqW+35TOOBpKeKnH7R+xc1wNomuEXQNq6BvJOK0h8wys2mQ5fJO4ssUhdkULe2+Y5OAVYp2lD4i75+HCE1AHPJOmwpxPLYmoScvVGWaKZ0jM8fml43+2HdmFfSsUk87a3tZ9f5NXpEwV3J6XFY9Lfh3/RqjE733JZF9abnzq5H55J7qhizIVOUgmnHCHqzLKPoQY8qeChj7dCirTV/0Yx8YGcQ7DNTIDrMIpbs=

# Deploy when pushing to master or develop
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
      all_branches: true
