language: php
php:
- '5.6'
- '7.0'
- '7.1'
addons:
  apt:
    packages:
    - sshpass
install:
- composer install --no-interaction
- composer dump-autoload -o
env:
  global:
    - DEPLOY_HOST=lin.freesewing.org
    - DEPLOY_USER=travis
    - DEPLOY_PATH=/fs/deploy/core/
script:
    - phpunit
    - ./scripts/test.sh
deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: true
  on:
    all_branches: true
