defaults:
    service: draft
    channel: Docs
    draftTheme: Basic
    sampleTheme: Sampler
    compareTheme: Compare
    infoTheme: Info
    pattern: TestPattern
    locale: en
renderers:
    svg: SvgRenderbot
    js: JsRenderbot
services:
    - info
    - draft
    - sample
    - compare
