defaults:
    service: draft
    channel: Docs
    draftTheme: Svg
    sampleTheme: Sampler
    infoTheme: Info
    pattern: AidenAshirt
    partMargin: 10
renderers:
    svg: SvgRenderbot
    js: JsRenderbot
services:
    - info
    - draft
    - sample
