defaults:
    service: draft
    channel: Freesewing
    draftTheme: Basic
    sampleTheme: Sampler
    compareTheme: Compare
    infoTheme: Info
    pattern: TestPattern
    locale: en

services:
    - info
    - draft
    - sample
    - compare

patternNamespaces:
    - Core
    - Contrib
    - Docs
    - Tests

themeNamespaces:
    - Core

channelNamespaces:
    - Core
