info:
  name:     "Tamiko Top"
  version:  "2.0"
  date:     "20161124"
  author:   "Joost De Cock"
  email:    "joost@decock.org"
  company:  "freesewing.org"
  link:     "freesewing.org/pattern/tamiko-top/"
parts:
  top:   "Tamiko Top"
languages:
    en: English
    nl: Nederlands
measurements:
    - acrossBack
    - chestCircumference
    - centerBackNeckToWaist
    - naturalWaistToHip
options:
    - lengthBonus
