info:
    name: "Lesley Leggings"
    version: "1.0"
    date: 20170121
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"

parts:
    .frame: "Frame"
    frontBlock: "Front base"
    backBlock: "Back base"
    frontSelvedgeBlock: "Front"
    backSelvedgeBlock: "Back"
    leggings: "Leggings"

languages:
    en: "English"

measurements:
    hipsCircumference: 950
    seatCircumference: 1045
    inseam: 910
    outseam: 1070
    naturalWaistToHip: 120
    naturalWaistToSeat: 260
    bodyRise: 320
    ankleCircumference: 255
    kneeCircumference: 420
    upperLegCircumference: 620

options:
    stretchFactor:
        type: "percent"
        default: 85
    lengthBonus:
        type: "measure"
        min: -200
        max: 100
        default: 50
