info:
    name: "Aaron A-Shirt"
    version: "2.0"
    date: 20161008
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    link: "freesewing.org/pattern/aaron-ashirt/"
parts:
    frontBlock: "Front block"
    backBlock: "Back block"
    front: Front
    back: Back
languages:
    en: English
    nl: Nederlands
measurements:
    - acrossBack
    - bicepsCircumference
    - centerBackNeckToWaist
    - chestCircumference
    - naturalWaistToHip
    - neckCircumference
    - shoulderLength
    - shoulderSlope
    - hipsCircumference
options:
    - chestEase
    - armholeDrop
    - lengthBonus
    - necklineBend
    - backlineBend
    - necklineDrop
    - shoulderStrapWidth
    - shoulderStrapPlacement
    - stretchFactor
    - hipsEase
inMemoryOf:   
    name: "Aaron Swartz"
    link: "https://en.wikipedia.org/wiki/Aaron_Swartz"
