info:
    name: "Seth Selvedge Trouser Block"
    description: "This is the Trent block adapted for selvedge designs"
    handle: "seth"
    version: "0.2"
    date: 20170121
    author: "Joost De Cock"
    company: "freesewing.org"
    tags:
        - menswear
        - trousers
        - block
        - bottom
          
parts:
    .frame: "Frame"
    frontBlock: "Front base"
    backBlock: "Back base"
    frontSelvedgeBlock: "Front"
    backSelvedgeBlock: "Back"

languages:
    en: "English"

measurements:
    hipsCircumference: 950
    seatCircumference: 1045
    inseam: 910
    outseam: 1070
    naturalWaistToHip: 120
    naturalWaistToSeat: 260
    bodyRise: 320

options:
    hipsEase:
        title: "Hips ease"
        description: "The of ease at the hips."
        group: "fit"
        type: "measure"
        min: 10
        max: 60
        default: 30
    seatEase:
        title: "Seat ease"
        description: "The amount of ease at your butt."
        group: "fit"
        type: "measure"
        min: 60
        max: 160
        default: 100
    crotchCurveFactor:
        title: "Crotch curve factor"
        description: "A factor the influences the shape of the crotch curve."
        group: "fit"
        type: "percent"
        default: 50
    backSeamCurveFactor:
        title: "Back seam curve factor"
        description: "A factor the influences the shape of the back seam."
        group: "fit"
        type: "percent"
        default: 50
