info:
     name:     "Cathrin Corset"
     version:  "2.0"
     date:     "20161i104"
     author:   "Joost De Cock"
     email:    "joost@decock.org"
     company:  "freesewing.org"
     link:     "freesewing.org/pattern/cathrin-corset/"
parts:
    base: "Base block"
    panels: "Corset"
languages:
    en: English
    nl: Nederlands
measurements:
    - underBust
    - naturalWaist
    - hips
    - naturalWaistToUnderbust 
    - naturalWaistToHips
options:
    - backOpening
    - waistReduction
    - frontRise
    - frontDrop
    - backRise
    - backDrop
    - hipRise
    - panels
