templates:
    js: 
        - "js/designer.js"
    css: 
        - "css/designer.css"
    defs: 
        - "defs/designer"
settings:
    partMargin: 10
    isPaperless: false
options:
    - parts
    - forceParts
    - onlyPoints
    - markPoints
