info:
  name: "Body Block Joost"
  version: "2.0"
  date: 20160925
  author: "Joost De Cock"
  email: "joost@decock.org"
  company: "freesewing.org"
  link: "freesewing.org/pattern/joost-body-block/"
parts:
  backBlock: "Back block"
  frontBlock: "Front block"
  sleeveBlock: "Sleeve block"
languages:
    en: English
    nl: Nederlands
measurements:
    - acrossBack
    - bicepsCircumference
    - centerBackNeckToWaist
    - chestCircumference
    - hipsCircumference
    - naturalWaistToHip
    - neckCircumference
    - shoulderLength
    - shoulderSlope
    - sleeveLengthToWrist  
    - wristCircumference
options:
    - chestEase
    - bicepsEase
    - cuffEase
