hidden: true
info:
    name: "Pattern notation legend"
    version: "1.0"
    date: 20180818
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"

parts:
    part: "A part"

languages:
    en: "English"

measurements:
    exampleMeasurement: 520

options:
    item:
        type: "chooseOne"
        default: "seamline"
