info:
    name: "Aiden A-Shirt"
    version: "2.0"
    date: 20161008
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    link: "freesewing.org/pattern/aiden-shirt/"
parts:
    front: Front
    back: Back

