info:
    name: "Aiden A-Shirt"
    version: "2.0"
    date: 20161008
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    link: "freesewing.org/pattern/aiden-shirt/"
parts:
    frontBlock: "Front block"
    backBlock: "Back block"
    front: Front
    back: Back
languages:
    en: English
    nl: Nederlands
