hidden: true
info:
    name: "Bent Body Block"
    description: "This block with a two-part sleeve is the basis of our menswear coat and jacket patterns"
    handle: "bent"
    version: "0.3"
    author: "Joost De Cock"
    company: "freesewing.org"
    link: "freesewing.org/pattern/bent"
    tags:
        - menswear
        - top
        - block

parts:
  backBlock: "Back block"
  frontBlock: "Front block"
  sleeveBlock: "Sleeve block"
  topsleeveBlock: "Topsleeve block"
  undersleeveBlock: "Undersleeve block"

languages:
    en: English
    nl: Nederlands
    fr: French

measurements:
    acrossBack: 450
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderToShoulder: 470
    shoulderSlope: 55
    hipsCircumference: 950
    sleeveLengthToWrist: 700
    wristCircumference: 190
    shoulderToElbow: 410 

options:
    chestEase:
        title: "Chest ease"
        description: "The amount of ease at your chest"
        group: "fit"
        type: measure
        min: -40
        max: 160
        default: 30
    bicepsEase:
        title: "Biceps ease"
        description: "The amount of ease at your upper arm"
        group: "fit"
        type: measure
        min: 0
        max: 80
        default: 30
    cuffEase:
        title: "Cuff ease"
        description: "The amount of ease at your wrist"
        group: "fit"
        type: measure
        min: 0
        max: 100
        default: 45
    armholeDepthFactor:
        title: "Armhole depth factor"
        description: "A factor that influences the depth of the armhole"
        group: "fit"
        type: "percent"
        min: 50
        max: 65
        default: 60
    sleevecapHeightFactor:
        title: "Sleevecap height factor"
        description: "A factor that influences the height of the sleevecap"
        group: "fit"
        type: "percent"
        min: 45
        max: 60
        default: 50
    sleevecapEase:
        title: "Sleevecap ease"
        description: "The ease on the sleevecap"
        group: "fit"
        type: "measure"
        min: 0
        max: 35
        default: 5
    sleeveBend:
        title: "Sleeve bend"
        description: "How much do you want the sleeve to be bent at the elbow"
        group: "fit"
        type: "angle"
        min: 0
        max: 20
        default: 10
    lengthBonus:
        title: "Length bonus"
        description: "Amount to lengthen the body. A negative value will shorten it."
        group: "fit"
        type: "measure"
        min: -40
        max: 120
        default: 0

