info:
  name:     "Trayvon Tie"
  version:  "2.0"
  author:   "Joost De Cock"
  email:    "joost@decock.org"
  company:  "freesewing.org"
  link:     "freesewing.org/pattern/trayvon"

parts:
  interfacingTip:   "Interfacing tip"
  interfacingTail:  "Interfacing tail"
  fabricTip:        "Fabric tip"
  fabricTail:       "Fabric tail"
  liningTip:        "Lining tip"
  liningTail:       "Lining tail"
  loop:             "Loop"

languages:
    en: English
    nl: Nederlands
    fr: French

measurements:
    centerBackNeckToWaist: 480
    neckCircumference: 420

options:
    tipWidth:
        type: measure
        min: 20
        max: 120
        default: 60
    knotWidth:
        type: measure
        min: 20
        max: 70
        default: 35

inMemoryOf:
    name: "Trayvon Martin"
    link: "https://en.wikipedia.org/wiki/Trayvon_Martin"
