info:
     name:         "Bruce Boxer Briefs"
     version:      "2.0"
     date:         "20161031"
     author:       "Joost De Cock"
     email:        "joost@decock.org"
     company:      "freesewing.org"
     link:         "freesewing.org/pattern/bruce-boxer-briefs/"
parts:
    front:    "Front"
    back:     "Back"
    side:     "Side"
    inset:    "Inset"
languages:
    en: English
    nl: Nederlands
measurements:
    hipsCircumference: 960
    upperLegCircumference: 600
    crossseamLength: 670
options:
    rise:
        type: "measure"
        min: 0
        max: 80
        default: 35

    verticalStretchFactor:
        type: "percent"
        default: 90

    horizontalStretchFactor:
        type: "percent"
        default: 80
