hidden: true
info:
    name: "Lesley Leggings"
    handle: "lesley"
    description: "A unisex leggings pattern"
    version: "0.4"
    date: 20170121
    author: "Joost De Cock"
    email: "joost@decock.org"
    company: "freesewing.org"
    tags:
        - unisex
        - leggings
        - bottom

parts:
    .frame: "Frame"
    frontBlock: "Front base"
    backBlock: "Back base"
    frontSelvedgeBlock: "Front"
    backSelvedgeBlock: "Back"
    leggings: "Leggings"

languages:
    en: "English"

measurements:
    hipsCircumference: 950
    seatCircumference: 1045
    inseam: 910
    outseam: 1070
    naturalWaistToHip: 120
    naturalWaistToSeat: 260
    seatDepth: 320
    ankleCircumference: 255
    kneeCircumference: 420
    upperLegCircumference: 620

options:
    stretchFactor:
        title: "Stretch factor"
        description: "The amount of negative ease. 100% means no negative ease, 90% mean 10% negative ease."
        group: "fit"
        type: "percent"
        default: 85
    lengthBonus:
        title: "Length bonus"
        description: "The amount by which to lengthen the legs. Negative values shorten them."
        group: "fit"
        type: "measure"
        min: -200
        max: 100
        default: 50
