Measurements:
    wristCircumference      : 'wristCircumference'
    chestCircumference      : 'chestCircumference'
    centerBackNeckToWaist   : 'centerBackNeckToWaist'
    acrossBack              : 'acrossBack'
    neckCircumference       : 'neckCircumference'
    hipsCircumference       : 'hipsCircumference'
    naturalWaistToHip       : 'naturalWaistToHip'
    shoulderLength          : 'shoulderLength'
    shoulderSlope           : 'shoulderSlope'
    bicepsCircumference     : 'bicepsCircumference'
    sleeveLengthToWrist     : 'sleeveLengthToWrist'
cmoptions:
    shoulderStrapWidth  : 'shoulderStrapWidth'
    necklineDrop        : 'necklineDrop'
    lengthBonus         : 'lengthBonus'
    armholeDrop         : 'armholeDrop'
    sleevecapEase       : 'sleevecapEase'
    collarEase          : 'collarEase'
    cuffEase            : 'cuffEase'
    chestEase           : 'chestEase'
    hipsEase            : 'hipsEase'
    bicepsEase          : 'bicepsEase'
    backNeckCutout      : 'backNeckCutout'

    backOpening         : 'backOpening'
    waistReduction      : 'waistReduction'
    frontRise           : 'frontRise'    
    frontDrop           : 'frontDrop'    
    backRise            : 'backRise'    
    backDrop            : 'backDrop'    
    hipRise             : 'panels'    
percentoptions:
    stretchFactor           : 'stretchFactor'
    shoulderStrapPlacement  : 'shoulderStrapPlacement'
    necklineBend            : 'necklineBend'
    backlineBend            : 'backlineBend'

