measurements:
    wc    : 'wristCircumference'
    cc    : 'chestCircumference'
    cbntw : 'centerBackNeckToWaist'
    ab    : 'acrossBack'
    nc    : 'neckCircumference'
    hc    : 'hipsCircumference'
    nwttw : 'naturalWaistToTrouserWaist'
    sl    : 'shoulderLength'
    ss    : 'shoulderSlope'
    ubc   : 'upperBicepsCircumference'
    slw   : 'sleeveLengthToWrist'
cmoptions:
    opt_ssw : 'shoulderStrapWidth'
    opt_nd  : 'necklineDrop'
    opt_lb  : 'lengthBonus'
    opt_ad  : 'armholeDrop'
    opt_se  : 'sleevecapEase'
    opt_ce  : 'collarEase'
    opt_cfe : 'cuffEase'
    opt_che : 'chestEase'
    opt_be  : 'bicepsEase'
    opt_bnc : 'backNeckCutout'
percentoptions:
    opt_sf  : 'stretchFactor'
    opt_ssp : 'shoulderStrapPlacement'
    opt_nb  : 'necklineBend'
    opt_bb  : 'backlineBend'
