info:
     name:     "Cathrin Corset"
     version:  "2.0"
     author:   "Joost De Cock"
     email:    "joost@decock.org"
     company:  "freesewing.org"
     link:     "freesewing.org/pattern/cathrin-corset/"

parts:
    base: "Base block"
    panels: "Corset"

languages:
    en: English
    nl: Nederlands
    fr: French

measurements:
    underBust: 720
    naturalWaist: 640
    hips: 800
    naturalWaistToUnderbust: 100
    naturalWaistToHips: 160

options:
    backOpening:
        type: measure
        min: 0
        max: 80
        default: 30
    waistReduction:
        type: measure
        min: 0
        max: 125
        default: 80
    frontRise:
        type: measure
        min: -50
        max: 50
        default: 25
    frontDrop:
        type: measure
        min: -30
        max: 50
        default: 25
    backRise:
        type: measure
        min: -30
        max: 120
        default: 0
    backDrop:
        type: measure
        min: -30
        max: 30
        default: 0
    hipRise:
        type: measure
        min: 0
        max: 60
        default: 30
    panels:
        type: chooseOne
        options:
            11: 11
            13: 13
        default: 13
