info:
     name:         "Benno Boxer Briefs"
     version:      "2.0"
     date:         "20161031"
     author:       "Joost De Cock"
     email:        "joost@decock.org"
     company:      "freesewing.org"
     link:         "freesewing.org/pattern/benno-boxer-briefs/"
parts:
    front:    "Front"
    back:     "Back"
    side:     "Side"
    inset:    "Inset"
languages:
    en: English
    nl: Nederlands
measurements:
    - hipsCircumference
    - upperLegCircumference
    - crossseamLength
options:
    - rise
    - verticalStretchFactor
    - horizontalStretchFactor
inMemoryOf:   
    name: "Benno Ohnesorg"
    link: "https://en.wikipedia.org/wiki/Benno_Ohnesorg"
