info:
    name: "Trent Trouser Block"
    version: "0.4"
    date: 20170324
    author: "Joost De Cock"
    company: "freesewing.org"
    link: "freesewing.org/pattern/trent"

parts:
    .frame: "Frame"
    frontBlock: "Front"
    backBlock: "Back"

languages:
    en: "English"

measurements:
    hipsCircumference: 950
    seatCircumference: 1045
    inseam: 910
    outseam: 1070
    naturalWaistToHip: 120
    naturalWaistToSeat: 260
    bodyRise: 320

options:
    hipsEase:
        type: "measure"
        min: 10
        max: 60
        default: 30
    seatEase:
        type: "measure"
        min: 60
        max: 160
        default: 100
    crotchCurveFactor:
        type: "percent"
        default: 50
    backSeamCurveFactor:
        type: "percent"
        default: 50
