measurements:
    wristCircumference      : 'wristCircumference'
    chestCircumference      : 'chestCircumference'
    centerBackNeckToWaist   : 'centerBackNeckToWaist'
    acrossBack              : 'acrossBack'
    neckCircumference       : 'neckCircumference'
    hipsCircumference       : 'hipsCircumference'
    naturalWaistToHip       : 'naturalWaistToHip'
    shoulderLength          : 'shoulderLength'
    shoulderSlope           : 'shoulderSlope'
    bicepsCircumference     : 'bicepsCircumference'
    sleeveLengthToWrist     : 'sleeveLengthToWrist'
    headCircumference       : 'headCircumerence'
cmoptions:
    shoulderStrapWidth  : 'shoulderStrapWidth'
    necklineDrop        : 'necklineDrop'
    lengthBonus         : 'lengthBonus'
    armholeDrop         : 'armholeDrop'
    sleevecapEase       : 'sleevecapEase'
    collarEase          : 'collarEase'
    cuffEase            : 'cuffEase'
    chestEase           : 'chestEase'
    hipsEase            : 'hipsEase'
    bicepsEase          : 'bicepsEase'
    backNeckCutout      : 'backNeckCutout'
percentoptions:
    stretchFactor           : 'stretchFactor'
    shoulderStrapPlacement  : 'shoulderStrapPlacement'
    necklineBend            : 'necklineBend'
    backlineBend            : 'backlineBend'
    ribbingStretchFactor    : 'ribbingStretchFactor'

