info:
  name: "Sven Sweatshirt"
  version: "1.0"
  date: 20170323
  author: "Joost De Cock"
  email: "joost@decock.org"
  company: "freesewing.org"
  link: "freesewing.org/pattern/sven"

parts:
  backBlock: "Back block"
  frontBlock: "Front block"
  sleeveBlock: "Sleeve block"
  back: "Back"
  front: "Front"
  sleeve: "Sleeve"

languages:
    en: "English"

measurements:
    acrossBack: 450
    bicepsCircumference: 335
    centerBackNeckToWaist: 480
    chestCircumference: 1080
    naturalWaist: 885
    naturalWaistToHip: 120
    neckCircumference: 420
    shoulderSlope: 55
    shoulderToShoulder: 470
    hipsCircumference: 950
    sleeveLengthToWrist: 700
    wristCircumference: 190

options:
    chestEase:
        type: "measure"
        min: -40
        max: 160
        default: 30
    bicepsEase:
        type: "measure"
        min: 40
        max: 120
        default: 80
    cuffEase:
        type: "measure"
        min: 0
        max: 100
        default: 60
    lengthBonus:
        type: "measure"
        min: 0
        max: 220
        default: 120
    sleeveLengthBonus:
        type: "measure"
        min: -40
        max: 80
        default: 60

